# Find the Dockerfile at this URL
# https://github.com/Azure/azure-functions-docker/tree/dev
# https://mcr.microsoft.com/en-us/artifact/mar/azure-functions/powershell/tags

# FROM mcr.microsoft.com/azure-functions/powershell:4-powershell7.2-core-tools
FROM mcr.microsoft.com/azure-functions/powershell:4-powershell7.4
